language: gcc

matrix:
  include:
    - env:
        - FC=pgf90
    - addons:
        apt:
          packages:
          - gfortran
          - libfftw3-dev
      env:
        - FC=gfortran

before_install:
  - if [[ ${FC} == "pgf90" ]]; then bash CI/install-pgi.sh --mpi; fi

script:
  - ${FC}


